train : "./data/trainset.json"
test  : "./data/testset.json"
train_dataloader : "./data/cache/train_target.pkl"
test_dataloader  : "./data/cache/test_target.pkl"
images           : "./data/images"
language_embeddings_folder : "./embeddings/language"
vision_embeddings_folder: "./embeddings/vision"
results_folder : "./results"
# parameters that can be changed
language_model_name : "emilyalsentzer/Bio_ClinicalBERT"
vision_model_name : "convnext_base"
experiment_name: "bioclinicalBERT_convnext"
